### ISSUE TITLE
isSolved executes after fragment is closed

### ISSUE THREAD

**Issue by alexanderberry** [TheCompSciNoob/MinigameMarathon#8]
While playing BinaryGame, isSolved continued to affirm its execution in the debug messages, meaning isSolved continues to execute even after the fragment is switched.

`10-03 15:41:08.344 28743-28743/com.example.chow.minigamemarathon D/LightsOut Game: isSolved: true`

**Comment by kyroschow** [comment]
isSolved continues to execute because for some reason the CountDownTimer cannot be stopped in the onTick() method. The Stopwatch can be stopped when cancel() is called outside the CountDownTimer thread. The problem here is that GameFragment detects game state changes using the game clock instead of detecting game changes after user input. The solution is to make all game state updates user-input driven or event driven (instead of time driven). So we would have to manually tell the clock to stop when the game is solved.

**Comment by alexanderberry** [comment]
Solved by 060fc62746d397fb9f27bdcfb8a128df0f8ae940
